In [17]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
print (a)
b = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]]) #matrix
print (b)
print (a.shape,b.shape) #Dimensions
type(a) #Type of array
b.dtype #Another way to write it
print (np.min(a),np.max(b)) #Min and max of the array
a.argmax()
c = np.arange(0,10) # Array of integer numbers from 0,9
d = np.arange(0,11,2) # Array of integers from 0 to 10 in steps of 2
print (c,d)
e = np.linspace(0,100,50) # Array of numbers from 0 to 100 with 50 spaces
print (e)
e.shape
f=np.arange(0,25) 
#print (f)
#f.reshape(25,1) #Reshape in columns
print (f)
#g=np.zeros(3)
g=np.zeros(shape=(3,3)) #Matrix with zeros
gg = 3. * (g + 1) #Exercise 1
print (g)
print (gg)
h=np.ones(shape=(2,3))
print (h)
hh=h / 2 - 1.#Exercise 2
print (hh)
o=np.eye(3) #DIagonal Matrix
print (o)
oo= o + gg #Exercise 3
print(oo)
x1 = np.random.randn(2,10) #Ten random numbers from 0. to 2.
print (x1)
x2 = np.random.randint(0,20,5) #Five random integers from 0 to 20
print (x2)
#Idexing example. This is choose the number with the index indicated
x3 = np.array([4,2,3,13,5,7,14])
#x3[3] #The third value of the array (It starts in 0)
print(x3[3])
#Slicing example
#x3[:5] #Taking the first five numbers of the array
print(x3[:5])
#Extracting a number from the array. This is, it removes all the numbers but the one indicated
#x3[-2] #If the index is negative it will start from the last number of the array
print(x3[-2])
#including evereything but the last member of the array
#x3[:-1]
s = (x3[-2]) ** 0.5 #Exercise 4
print(s)
print(x3[:-1])
#erase = x3[:-1]
#flipping the array
x3[::-1]
#erase = x3[::-1]





[0 1 2 3 4 5 6 7 8 9]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
(10,) (3, 3)
0 9.0
[0 1 2 3 4 5 6 7 8 9] [ 0  2  4  6  8 10]
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[-0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5]]
[[1. 0.

array([14,  7,  5, 13,  3,  2,  4])