In [421]:
import numpy as np

# Generating one-dimensional (1D) array.

In [422]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [423]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Generating two-dimensional (2D) array.

In [424]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [425]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Checking the size or dimension of the array.

In [426]:
a.shape

(10,)

In [427]:
b.shape

(3, 3)

In [428]:
# Exercise 02: Array C is a matrix of 4 by 5 with sequential numbers from 20 to 39. Write the matrix and find the dimensions.

# Check the type

In [429]:
type(a)

numpy.ndarray

In [430]:
type(b)

numpy.ndarray

In [431]:
a.dtype

dtype('int32')

In [432]:
b.dtype

dtype('int32')

# Maximum and Minimum values

In [433]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [434]:
np.max(a)

9

In [435]:
np.min(a)

0

# Index of maximum and minimum values

In [436]:
a = np.array([4,2,3,13,5,7,14])

In [437]:
max(a)

14

In [438]:
a.max()    # finding maximum value

14

In [439]:
a.argmax() # index of maximum value

6

In [440]:
a.min()  # finding minimum value

2

In [441]:
a.argmin() # index of minimum value

1

# arange

In [442]:
c = np.arange(0,10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [443]:
d = np.arange(0,11,2)
d

array([ 0,  2,  4,  6,  8, 10])

In [444]:
e = np.arange(0,101,20)
e

array([  0,  20,  40,  60,  80, 100])

In [445]:
# Exercise 3: Write an arithmetic sequence from increments of 1/5 from 0 to 5 

# linspace

In [446]:
x1 = np.linspace(0,20,5)
x1

array([ 0.,  5., 10., 15., 20.])

In [447]:
x2 = np.linspace(0,10,3)

In [448]:
x2

array([ 0.,  5., 10.])

In [449]:
x3 = np.linspace(0,10,50)

In [450]:
x3

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [451]:
x3.shape

(50,)

In [452]:
#Exercise 04: Divide the interval from -5 to 20 in 20 steps.

# reshape

In [453]:
y = np.arange(0,25)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [454]:
y.shape

(25,)

In [455]:
y.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [456]:
y.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [457]:
y.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

# zeros and ones

In [458]:
np.zeros(3)

array([0., 0., 0.])

In [459]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [460]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [461]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [462]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [463]:
7 * np.ones((3,3))

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [464]:
# Exercise 05: Convert a 5 by 6 matrix of ones to a 5 by 6 matrix of -0.5

In [465]:
# Exercise 06: Change the values of a 3 by matrix with ones to a matrix with 3's using a 1 and a 3.

# eye, generating Identity matrix

In [466]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [467]:
# Exercise 07: Add the matrix from exercise 06 to the last identity matrix

# Random Numbers

## randn 

In [468]:
x1 = np.random.randn(3,3)                    # will generate random numbers from normal distribution.
x1

array([[ 0.36349409,  0.56981238, -0.55655376],
       [-0.26582074,  0.46167697, -0.05942542],
       [ 0.16493516,  0.75648691,  0.24828828]])

## rand

In [469]:
x2 = np.random.rand(3,3)                          # will generate random numbers between 0 and 1.
x2

array([[0.80218319, 0.73324305, 0.62733524],
       [0.24732374, 0.21041424, 0.93779567],
       [0.660967  , 0.27851879, 0.67741728]])

## randint

In [470]:
x3 = np.random.randint(3,8,10)                  # will generate 10 random integers between 3 and 8.
x3

array([3, 4, 4, 5, 5, 3, 6, 3, 4, 4])

In [492]:
# Quiz01: Create an array from 1 to 16. Use the command y = np.resahpe(arr,(n,m)) to create 4x4 matrix from the first array. 
# Multiply the matrix by a 4X4 identity matrix


# Indexing and Slicing

## Indexing and slicing with 1D array

In [472]:
ar = np.array([4,2,3,13,5,7,14])

In [473]:
ar[3]  # Indexing

13

In [474]:
ar[6]

14

In [475]:
ar[1:4]  # Slicing

array([ 2,  3, 13])

In [476]:
ar[-1]  # Extracting last member of array.

14

In [477]:
ar[-2] # Extracting second last memeber of array

7

In [478]:
ar[1:]  # Slicing from index 1 to end.

array([ 2,  3, 13,  5,  7, 14])

In [479]:
ar[:4]  # slicing upto index 3

array([ 4,  2,  3, 13])

In [480]:
ar[:-1]  # Include everything except the last member of array

array([ 4,  2,  3, 13,  5,  7])

In [481]:
ar[::-1]  # Reversing or flipping the array

array([14,  7,  5, 13,  3,  2,  4])

In [482]:
# Exercise 08: Find the square root of the second the last number of the last array.

## Indexing of sub-array and sub-matrix from 2D (matrix) array 

In [483]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [484]:
arr[0] # Extracting first row

array([1, 2, 3, 4])

In [485]:
arr[3] # Extracting last row

array([13, 14, 15, 16])

In [486]:
arr[2][1]

10

In [487]:
arr[2,1] # Other method

10

In [488]:
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [489]:
arr[:,3]   # Extracting last column

array([ 4,  8, 12, 16])

In [490]:
arr[:,3].reshape(-1,1)  # Extracting last column vertically

array([[ 4],
       [ 8],
       [12],
       [16]])

In [491]:
arr[:,3:]  # Other way of Extracting last column vertically

array([[ 4],
       [ 8],
       [12],
       [16]])